services:

  app:
    image: ghcr.io/maybe-finance/maybe:latest
    ports:
      - 127.0.0.1:3000:3000
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: "postgres"
      RAILS_ENV: "production"
      RAILS_FORCE_SSL: false
      RAILS_ASSUME_SSL: false
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
